# Generated by Django 3.0.2 on 2022-06-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0002_auto_20220608_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrubric',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Имя рубрики'),
        ),
    ]
