# Generated by Django 3.0.2 on 2022-06-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_core', '0003_auto_20220610_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='images',
            field=models.ImageField(blank=True, upload_to='post_img/', verbose_name='Изображение'),
        ),
    ]
